### ISSUE TITLE
emulator: ERROR: Could not load OpenGLES emulation library: lib64OpenglRender.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by allanian** [tracer0tong/android-emulator#25]
When you use this image in GITLAB, you get this error:
emulator: ERROR: Could not load OpenGLES emulation library: lib64OpenglRender.so: cannot open shared object file: No such file or directory
Can you help me?

image: tracer0tong/android-emulator:latest
stages:
  - build
  
build:
  stage: build
  script:
   - cat > "filename".txt

**Comment by tracer0tong** [comment]
I'm creating AVD without hardware acceleration for 3D graphics (-gpu off), it should use software rendering instead of OpenGL. So, I'm quite surprised that it tries to load library, instead of showing warning to you. Try to check https://askubuntu.com/questions/364980/ubuntu-12-04-andorid-virtual-device-android-virtual-device-not-starting-up, probably you just missed 64-bit version from your library path.
